[workspace]
default-members = ["apps/*"]
members = [
    "apps/editor",
    "crates/broker",
    "crates/editor",
    "crates/editor",
    "crates/rpc",
    "crates/ui",
    "crates/widget",
    "crates/widgets/*",
]
resolver = "2"
